python guacamoliency/modeling/train.py \
    --tokenizer_path data/tokenizers_blocksmiles/moses_canonical_conditional \
    --tokenizer_type "blocksmiles" \
    --datasets blocksmiles_conditional_maxweight\
    --log_dir reports \
    --dataset_dir data/training_data/blocksmiles_maxweight.csv \
    --model_save_folder models/trained_moses_blocksmiles_conditional\
    --learning_rate 6e-4 \
    --max_steps 826000\
    --batch_size 192\
    --save_steps 8260\
    --save_total_limit 100\
    --warmup_steps 826