python guacamoliency/modeling/train.py --tokenizer_path data/tokenizers_character_level/guacamol_and_moses_canonical \
    --tokenizer_type "character_level" \
    --datasets guacamol_and_moses_canonical \
    --log_dir reports \
    --dataset_dir data/training_data/guacamol_and_moses_canonical.csv \
    --model_save_folder models/trained_both_canonical \
    --learning_rate 6e-4 \
    --max_steps 91884 \
    --batch_size 384 \
    --save_steps 40000 \
    --warmup_steps 919 \
    --save_total_limit 3